import localFont from 'next/font/local';

import Header from 'components/header';

import 'styles/css/theme/global.css';

const comicSans = localFont({
  src: '../styles/fonts/comic-sans-ms.woff', 
  variable: '--font-comic-sans-ms'
});
const lucidaFax = localFont({
  src: '../styles/fonts/lucida-fax-regular-v2.woff',
  variable: '--font-lucida-fax'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css" />
      </head>
      <body className={`${lucidaFax.variable} ${comicSans.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
};