import localFont from 'next/font/local';

import { ThemeProvider } from 'context/theme-context';
import { SessionProvider } from 'context/user-context';

import Header from 'components/header';

import 'styles/css/theme/theme.css';


const comicSans = localFont({
  src: '../styles/fonts/comic-sans-ms.woff', 
  variable: '--font-comic-sans-ms'
});

const lucidaFax = localFont({
  src: '../styles/fonts/lucida-fax-regular-v2.woff',
  variable: '--font-lucida-fax'
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${lucidaFax.variable} ${comicSans.variable}`}>
        <ThemeProvider>
          <SessionProvider>
            <Header />
            <main>
              {children}
            </main>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};